load_module modules/ngx_http_morph_module.so;
thread_pool pool threads=128 max_queue=65535;

worker_processes  auto;
worker_rlimit_nofile 65535;

pid        logs/nginx.pid;

events {
    worker_connections  8192;
    use epoll;
    multi_accept on;
    accept_mutex off;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent ($request_time sec) "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"';

    server_tokens off;
    access_log off;

    tcp_nodelay     on;
    tcp_nopush      on;
    reset_timedout_connection on;
    client_header_timeout 10s;
    client_body_timeout 10s;
    send_timeout 10;

    sendfile        on;

    keepalive_timeout  15;
    keepalive_requests 1000;    

    server {
        listen       8080;
        server_name  localhost;

        location = /favicon.ico {
            return 204;
            access_log     off;
            log_not_found  off;
        }

        # Method Restriction
        if ($request_method = PUT) {
            return 415;
        }

        # Optimization for Large Images
        output_buffers 1 2m;
        client_max_body_size 10m;

        expires 120m; # Cache-Control: max-age=7200
        etag off;

        location /morph/ {
            aio threads=pool;
            
            root   /svc/morph/cache;
            add_header 'Access-Control-Allow-Origin' '*' always;

            # Security: Allow Purge (DELETE) only from localhost and specific IPs
            limit_except GET HEAD {
                allow 127.0.0.1;
                # allow 192.168.0.1; # Add admin IP here
                deny all;
            }

            morph_thumbnail;
            morph_debug on;

            # Morph module configuration
            quality 90;
            webp_quality 80;

            width_min  1;
            width_max  4000;
            height_min 1;
            height_max 4000;

            # Morph Service Purge/Storage Configuration
            service morph.conf;

            access_log  logs/accesslog/access.log main;
            error_log   logs/errorlog/error.log error;
        }

        error_page 403 404  /40x.html;
        location = /40x.html {
            root   html;
        }

        error_page 500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
    }
}
